select * from sales
-- Q1. Find the total sales revenue generated by each region.
SELECT
    region,
    SUM(sales_amount) AS total_sales_revenue
FROM sales
GROUP BY region
ORDER BY total_sales_revenue DESC;

-- Q2. Identify the top 5 sales representatives based on total sales revenue.
SELECT
    sales_rep,
    SUM(sales_amount) AS total_sales_revenue
FROM sales
GROUP BY sales_rep
ORDER BY total_sales_revenue DESC
LIMIT 5;

-- Q3. Calculate the average sales amount for each product category.
SELECT
    product_category,
    ROUND(AVG(sales_amount)::NUMERIC, 2) AS average_sales_amount
FROM sales
GROUP BY product_category
ORDER BY average_sales_amount DESC;

-- Q4. Find the product category that generated the highest total profit.
SELECT
    product_category,
    SUM((unit_price - unit_cost) * quantity_sold) AS total_profit
FROM sales
GROUP BY product_category
ORDER BY total_profit DESC
LIMIT 1;

-- Q5. Display the monthly sales revenue and identify the month with the highest sales.
SELECT
    TO_CHAR(sale_date, 'Month YYYY') AS month,
    SUM(sales_amount) AS total_sales_revenue
FROM sales
GROUP BY DATE_TRUNC('month', sale_date), TO_CHAR(sale_date, 'Month YYYY')
ORDER BY total_sales_revenue DESC;

-- Q6. Compare the total sales revenue and average sales amount between New and Returning customers.
SELECT
    customer_type,
    SUM(sales_amount) AS total_sales_revenue,
    ROUND(AVG(sales_amount)::NUMERIC, 2) AS average_sales_amount
FROM sales
GROUP BY customer_type;

-- Q7. Find the top 10 products based on total sales revenue.
SELECT
    product_id,
    SUM(sales_amount) AS total_sales_revenue
FROM sales
GROUP BY product_id
ORDER BY total_sales_revenue DESC
LIMIT 10;
-- Q8. Calculate the percentage contribution of each region to the company's total sales revenue.
SELECT
    region,
    SUM(sales_amount) AS total_sales_revenue,
    (SUM(sales_amount) * 100.0 /
     (SELECT SUM(sales_amount) FROM sales)) AS revenue_percentage
FROM sales
GROUP BY region
ORDER BY revenue_percentage DESC;

-- Q9. Find the sales representatives whose total sales revenue is greater than the average sales revenue of all sales representatives.
SELECT
    sales_rep,
    SUM(sales_amount) AS total_sales_revenue
FROM sales
GROUP BY sales_rep
HAVING SUM(sales_amount) >
(
    SELECT AVG(total_sales_revenue)
    FROM
    (
        SELECT
            sales_rep,
            SUM(sales_amount) AS total_sales_revenue
        FROM sales
        GROUP BY sales_rep
    ) AS avg_revenue
)
ORDER BY total_sales_revenue DESC;

-- Q10. Calculate the average discount offered for each sales channel and identify which channel offers the highest average discount.
SELECT
    sales_channel,
    ROUND(AVG(discount)::NUMERIC, 2) AS average_discount
FROM sales
GROUP BY sales_channel
ORDER BY average_discount DESC;